springboot 3 migration (#20)
springdoc-openapi-ui -> springdoc-openapi-starter-webmvc-ui for compatibility with springboot 3
openapi-webflux-ui -> openapi-starter-webflux-ui
wiremock 3 to fix NoClassDefFoundError: javax/servlet/DispatcherType
back to springboot 3.1.2 because of hibernate 6.2.7 HH-16811 regression in springboot 3.1.3

Signed-off-by: Abdelsalem <abdelsalem.hedhili@rte-france.com>
Signed-off-by: HARPER Jon <jon.harper87@gmail.com>